# Generated by Django 5.0.4 on 2024-06-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('auther', models.CharField(max_length=20)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.myuser')),
            ],
        ),
    ]
