# Generated by Django 5.0.4 on 2024-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DateField()),
                ('singer_name', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=20)),
                ('myuser', models.ManyToManyField(to='poll.myuser')),
            ],
        ),
    ]
